---

csr:
  hosts:
    csr1:
      ansible_host: 10.199.199.220
    csr2:
      ansible_host: 10.199.199.221
    csr3:
      ansible_host: 10.199.199.222
    csr4:
      ansible_host: 10.199.199.223

  vars:
    ansible_connection: network_cli 
    ansible_network_os: ios 
    ansible_ssh_pass: cisco 
    ansible_user: mobin
   
