l3_interfaces:
-   ipv4:
    -   address: 10.0.0.13/30
    name: GigabitEthernet1
-   ipv4:
    -   address: 10.0.0.10/30
    name: GigabitEthernet2
-   ipv4:
    -   address: 10.255.254.1/24
    name: GigabitEthernet3
-   ipv4:
    -   address: 10.199.199.223/24
    name: GigabitEthernet4
-   ipv4:
    -   address: 4.4.4.4/32
    name: Loopback0
ospfv2:
    processes:
    -   areas:
        -   area_id: '0'
            capability: true
        network:
        -   address: 4.4.4.4
            area: '0'
            wildcard_bits: 0.0.0.0
        -   address: 10.0.0.0
            area: '0'
            wildcard_bits: 0.0.0.255
        process_id: 1
        router_id: 4.4.4.4

